# Generated by Django 5.1.7 on 2025-10-13 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('mileage_km', models.PositiveIntegerField(default=0)),
                ('engine_volume_1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('power_hp', models.PositiveIntegerField(blank=True, null=True)),
                ('steering_wheel', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=8)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=8)),
                ('vin', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('price_kzt', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sold', 'Sold')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.bodytype')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.carmodel')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.city')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.color')),
                ('drive_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.drivetype')),
                ('features', models.ManyToManyField(blank=True, related_name='listings', to='catalog.feature')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.fueltype')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.generation')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.make')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.transmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'city', 'make', 'car_model'], name='listings_li_status_72f006_idx')],
            },
        ),
    ]
