# Generated by Django 5.1.7 on 2025-10-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='engine_volume_1',
            new_name='engine_volume_l',
        ),
    ]
