# Generated by Django 5.1.7 on 2025-12-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='generation',
            name='years',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
